package bim;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.*;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.net.URLClassLoader;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.BackingStoreException;
import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.plaf.synth.SynthLookAndFeel;
import javax.swing.table.TableModel;
import org.java.ayatana.ApplicationMenu;
import org.java.ayatana.AyatanaDesktop;

/**
 *
 * Compute the Body Mass Index - Copyright (C) 2012 - OTIKA –
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * Bomico - Copyright (C) 2012 <OTIKA – hanynowsky@gmail.com> This program comes
 * with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to
 * redistribute it under certain conditions.
 *
 * @version 1.0
 * @author hanynowsky@gmail.com
 * @since 1.0
 */
public class Bim extends javax.swing.JFrame {

    /**
     * Creates new form Bim
     */
    public Bim() {

        initComponents();

        /**
         * *
         * Call Java Swing Ayatana Library Check if environment supports Ayatana
         * Desktop
         */
        if (AyatanaDesktop.isSupported()) {
            ApplicationMenu.tryInstall(Bim.this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog(this);
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jOptionPane1 = new javax.swing.JOptionPane();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton8 = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        jButton9 = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSlider3 = new javax.swing.JSlider();
        jSlider4 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jTextField4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jSeparator16 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        jDialog1.setTitle("BOMICO");
        jDialog1.setMinimumSize(new java.awt.Dimension(410, 430));
        jDialog1.setModal(true);
        jDialog1.setResizable(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/pingu.png"))); // NOI18N
        jLabel5.setAlignmentX(0.5F);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Small program for computing the Body Mass Index");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Copyright © 2012 OTIKA");
        jLabel7.setAlignmentX(0.5F);

        jLabel8.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("BOMICO V1.0"+"-");

        jLabel9.setText("<html><a href=\"\"> </a>");

        jLabel10.setFont(new java.awt.Font("Liberation Mono", 1, 10)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("<html><a href=\"https://launchpad.net/~hanynowsky\">Website</a></html>");
        jLabel10.setAlignmentX(0.5F);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                goToWebSite(evt);
            }
        });

        jTextPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jTextPane1.setContentType("text/html");
        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextPane1.setText(new Utilities().getAppInfos()

        );
        jTextPane1.setMargin(new java.awt.Insets(8, 8, 8, 8));
        jTextPane1.setPreferredSize(new java.awt.Dimension(85, 16));
        jScrollPane2.setViewportView(jTextPane1);

        jButton5.setBackground(new java.awt.Color(223, 223, 223));
        jButton5.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton5.setText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(223, 223, 223));
        jButton6.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton6.setText("Credits");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(223, 223, 223));
        jButton7.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton7.setText("License");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel7)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addGap(13, 13, 13)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton5)
                    .addComponent(jButton6)))
        );

        jDialog1.getAccessibleContext().setAccessibleDescription("");
        jDialog1.setLocationRelativeTo(this);

        jDialog2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog2.setMinimumSize(new java.awt.Dimension(400, 400));
        jDialog2.setModal(true);

        jTable1.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jTable1.setModel(new Tmodel());
        jScrollPane3.setViewportView(jTable1);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("BIM Follow-up");

        jButton10.setBackground(new java.awt.Color(223, 223, 223));
        jButton10.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton10.setText("Close");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(jSeparator10)))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton10)))
                .addContainerGap())
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addContainerGap())
        );

        jDialog2.setLocationRelativeTo(this);

        jOptionPane1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/95.png"))); // NOI18N
        jOptionPane1.setMessage("Delete Follow-up File?");
        jOptionPane1.setMessageType(javax.swing.JOptionPane.QUESTION_MESSAGE);
        jOptionPane1.setOptionType(javax.swing.JOptionPane.YES_NO_OPTION);
        jOptionPane1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOMICO 1.0");
        setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        setMinimumSize(new java.awt.Dimension(850, 700));
        setPreferredSize(new java.awt.Dimension(875, 710));
        setResizable(false);
        getContentPane().setLayout(null);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jToolBar1.add(jSeparator6);

        jButton3.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/53.png"))); // NOI18N
        jButton3.setToolTipText("<html><font face=\"SansSerif\" size=\"3\">Exit</font>");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator4);

        jButton1.setBackground(new java.awt.Color(223, 223, 223));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/114.png"))); // NOI18N
        jButton1.setToolTipText("<html><font face=\"SansSerif\" size=\"3\">Calculate BMI</font>");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator5);

        jButton8.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/95.png"))); // NOI18N
        jButton8.setToolTipText("<html><font face=\"SansSerif\" size=\"3\">Follow-up</font>");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);
        jToolBar1.add(jSeparator14);

        jButton9.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/33.png"))); // NOI18N
        jButton9.setToolTipText("<html><font face=\"SansSerif\" size=\"3\">Save BMI</font>");
        jButton9.setEnabled(false);
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton9);
        jToolBar1.add(jSeparator15);

        jButton4.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/122.png"))); // NOI18N
        jButton4.setToolTipText("<html><font face=\"SansSerif\" size=\"3\">About Bomico</font>");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator13);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 880, 40);

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel17.setText("Body Mass Index Computer is Ready.");
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 670, 860, 30);

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(238, 238, 238));
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 770));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Weight");
        jLabel2.setAlignmentX(0.5F);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setText("Height");

        jSlider3.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jSlider3.setMaximum(160);
        jSlider3.setMinimum(15);
        jSlider3.setToolTipText("Weight");
        jSlider3.setValue(Integer.parseInt(utils.prefs.get(utils.WEIGHT_PREF, "60")));
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });

        jSlider4.setFont(new java.awt.Font("Ubuntu Light", 1, 12)); // NOI18N
        jSlider4.setMaximum(220);
        jSlider4.setMinimum(20);
        jSlider4.setToolTipText("Height");
        jSlider4.setValue(Integer.parseInt(utils.prefs.get(utils.HEIGHT_PREF, "170")));
        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider4StateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(74, 74, 74));
        jLabel4.setText("Gender");

        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jComboBox1.setSelectedItem((Object)(utils.prefs.get(utils.GENDER_PREF, "Male")));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(8);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jTextArea1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jTextArea1.setSelectedTextColor(new java.awt.Color(255, 102, 0));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel1.setText("BMI");
        jLabel1.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel11.setText("("+String.valueOf(jSlider3.getValue())+" Kg / "+utils.convertWeight(jSlider3.getValue())+" Pounds )");
        jLabel11.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel12.setText("("+String.valueOf(jSlider4.getValue())+" Cm / "+utils.convertHeight(jSlider4.getValue())+" )");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("..");
        jTextField1.setToolTipText("Social Ideal BMI");

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel13.setText("Ideal BMI");
        jLabel13.setToolTipText("");
        jLabel13.setEnabled(false);

        jSlider1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jSlider1.setMaximum(80);
        jSlider1.setMinimum(18);
        jSlider1.setToolTipText("Age Value");
        jSlider1.setValue(Integer.parseInt(new Utilities().prefs.get(new Utilities().AGE_PREF, "0")));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setText("Age");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 153, 51));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText(".");

        jButton2.setBackground(new java.awt.Color(223, 223, 223));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton2.setText("Compute");
        jButton2.setToolTipText("Compute");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("-----------");

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel15.setText("Status");
        jLabel15.setEnabled(false);

        jProgressBar1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jProgressBar1.setStringPainted(true);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setToolTipText("Social Ideal Weight");
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel18.setText("Ideal Weight");
        jLabel18.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel20.setText("("+String.valueOf(jSlider1.getValue())+" Y)");

        jComboBox2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Low Active", "Very Active", "Sedentary", "Extreme" }));
        jComboBox2.setSelectedItem((Object)(utils.prefs.get(utils.ACTIVITY_PREF, "Sedentary")));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(74, 74, 74));
        jLabel22.setText("Activity");
        jLabel22.setToolTipText("");

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel23.setText("iWeight Range");
        jLabel23.setToolTipText("");
        jLabel23.setEnabled(false);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jComboBox3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mesomorph", "Ectomorph", "Endomorph" }));
        jComboBox3.setSelectedItem((Object)(utils.prefs.get(utils.MORPH_PREF,"Mesomorph")));

        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(74, 74, 74));
        jLabel25.setText("Morpholgy");

        jLabel26.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(74, 74, 74));
        jLabel26.setText("Formula");

        jComboBox4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hamwi", "Miller", "Robinson", "Devine", "Social" }));
        jComboBox4.setSelectedItem((Object)(utils.prefs.get(utils.FORMULA_PREF, "Devine")));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel21.setText("EER (Kcal/day)");
        jLabel21.setToolTipText("");
        jLabel21.setEnabled(false);

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel24.setText("TDEE (Cal/Day)");
        jLabel24.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel19.setText("BMR (Cal/Day)");
        jLabel19.setEnabled(false);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText(".");

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText(".");

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, 97, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, 99, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(49, 49, 49)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator7)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator8)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator9)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel11)))
                .addGap(6, 6, 6)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(13, 13, 13)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel26)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addComponent(jButton2)))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BMI", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator16, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Miscelaneous", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 50, 860, 610);
        jTabbedPane1.getAccessibleContext().setAccessibleName("BMI");

        jMenu1.setForeground(new java.awt.Color(153, 153, 153));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExit(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        jMenuItem9.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jMenuItem9.setText("Delete File");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);
        jMenu1.add(jSeparator1);

        jMenu4.setText("Preferences");
        jMenu4.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jMenuItem12.setText("Save Preferences");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuItem13.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jMenuItem13.setText("Clear Preferences");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenu1.add(jMenu4);

        jMenu5.setText("Export");
        jMenu5.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jMenuItem4.setText("Follow-up");
        jMenuItem4.setToolTipText("");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem14.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jMenuItem14.setText("Results");
        jMenuItem14.setEnabled(false);
        jMenu5.add(jMenuItem14);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(153, 153, 153));
        jMenu2.setText("L&F");
        jMenu2.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jMenuItem5.setText("Metal");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jMenuItem6.setText("GTK");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jMenuItem7.setText("Nimbus");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jMenuItem8.setText("Motif");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem11.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jMenuItem11.setText("Liquid");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);
        jMenu2.add(jSeparator17);

        jMenuItem10.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jMenuItem10.setText("Synth");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(153, 153, 153));
        jMenu3.setText("About");
        jMenu3.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAbout(evt);
            }
        });
        jMenu3.add(jMenuItem1);
        jMenu3.add(jSeparator3);

        jMenuItem3.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jMenuItem3.setText("Clean");
        jMenuItem3.setName("Clean");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleDescription("Application for computing the Body Mass Index.");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * BMI Computation method for the GUI
     */
    private void computation() {
        
        //  Utilities utility = new Utilities();
        // double H = jSlider4.getValue() * 0.01;
        double W = jSlider3.getValue();
        //  Double d = new Double(Double.valueOf(W));
        //  double bimo = (d / (Math.pow(H, H)));
        DecimalFormat df = new DecimalFormat("#.##");
        res = c.computer(jSlider4.getValue(), W);
        String bmi = String.valueOf(df.format(res));
        //  jTextArea1.setLineWrap(true);
        jTextArea1.setText("You are a " + jComboBox1.getSelectedItem()
                + ", aged " + jSlider1.getValue() + ", who weighs "
                + jSlider3.getValue() + " Kgs" + ", and measures "
                + jSlider4.getValue() + " Cms" + " in height." + "\n");
        jTextArea1.append("Your BMI = " + bmi);
        jTextArea1.append("\n" + "(" + c.getHealthText() + " )");
        jTextField3.setText(c.getHealth());
        // System.out.println(String.valueOf(bimo));
        // System.out.println(res);
        System.err.println("BIM is: " + df.format(c.getResult()));
        jTextField2.setText(bmi);
        jButton9.setEnabled(true);
        System.out.println("Health Status - You are: " + c.getHealth());

        Color greencolor = new Color(0, 153, 51);
        Color redcolor = new Color(204, 0, 0);


        // Compute Ideals
        c.computePeopleIdeal(jSlider1.getValue(), jComboBox1.getSelectedItem().toString(), res);
        jTextField1.setText(String.valueOf(new DecimalFormat("#.##").format(c.getIdeal())));
        c.computeIdealWeight(jSlider4.getValue(), jComboBox4.getSelectedItem().toString(), jComboBox1.getSelectedItem().toString(), jComboBox3.getSelectedItem().toString());
        jTextField4.setText(String.valueOf(new DecimalFormat("#.##").format(c.getIweight())));
        c.computeEER(jSlider1.getValue(), jComboBox2.getSelectedItem().toString(), jSlider4.getValue(), jSlider3.getValue(), jComboBox1.getSelectedItem().toString());
        jTextField5.setText(new DecimalFormat("#.###").format(c.getEER() / 1000));

        double ih = (double) jSlider4.getValue();
        double h = ih / 100; // Transform from centimeters to meters.
        utils.readIBMITABLE(jComboBox1.getSelectedItem().toString(), h);
        System.err.println("Medical Weight Range is: " + utils.getIbmirange() + " for a height of:  " + h);

        //System.err.println(jComboBox1.getSelectedItem());

        jTextField6.setText(utils.getIbmirange());
        c.computeBMR(jSlider3.getValue(), jSlider4.getValue(), jSlider1.getValue(), jComboBox1.getSelectedItem().toString());
        c.computeTDEE(jComboBox2.getSelectedItem().toString());
        jTextField7.setText(String.valueOf(new DecimalFormat("#.##").format(c.getBMR())));
        jTextField8.setText(String.valueOf(new DecimalFormat("#.##").format(c.getTDEE())));


        if (18.5 <= res & res <= 25) {
            jTextField2.setForeground(greencolor);
            System.out.println("Normal BMI");
        }
        if (18.5 > res | res > 25) {
            jTextField2.setForeground(redcolor);
        }



        //
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (evt.getSource() == jButton1) {
            Task task = new Task();
            task.addPropertyChangeListener(new PropertyChangeListener() {

                @Override
                public void propertyChange(PropertyChangeEvent event) {
                    if ("progress".equals(event.getPropertyName())) {
                        int progress = (Integer) event.getNewValue();
                        jProgressBar1.setIndeterminate(false);
                        jProgressBar1.setValue(progress);
                        jLabel17.setText(String.format("Completed %d%% of task. ", progress));
                        // computation();
                    }
                    computation();
                }
            });
            task.execute();

            System.out.println("Computation Done.");
            jLabel17.setText("Computation done.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void displayAbout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAbout
        if (evt.getSource() == jMenuItem1) {
            System.out.println("About Dialog opened");
            jDialog1.setVisible(true);
            jDialog1.setSize(400, 500);
        };
    }//GEN-LAST:event_displayAbout

    private void menuExit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExit
        if (evt.getSource() == jMenuItem2) {
            this.addWindowListener(new ExitListener());
            System.exit(0);
        };
    }//GEN-LAST:event_menuExit

    private void goToWebSite(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToWebSite
        if (evt != null) {
            try {
                java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
                desktop.browse(new URI("https://launchpad.net/~hanynowsky"));


            } catch (IOException | URISyntaxException ex) {
                Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);//
            }
        }
    }//GEN-LAST:event_goToWebSite

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (evt.getSource() == jMenuItem3) {
            System.gc();
            jLabel17.setText("Resources liberated.");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    /**
     * Writes a File from a JTable model.
     *
     * @param table a JTable
     * @param file a File
     */
    public void toCSV(JTable table, File file) {
        try {
            TableModel model = table.getModel();
            try (FileWriter csv = new FileWriter(file)) {
// Writes the header of the Java Table
                for (int i = 0; i < model.getColumnCount(); i++) {
                    csv.write(model.getColumnName(i) + ";");
                }
                csv.write("\n");
// Parse the rows
                for (int i = 0; i < model.getRowCount(); i++) {
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        csv.write(model.getValueAt(i, j).toString() + ";");
                    }
                    csv.write("\n");


                }
            }

        } catch (IOException e) {
            Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, e);
            System.out.println(e);
        }
    }

    /**
     * This method has to be shortened somehow (repetitive code). Issue: The GTK
     * LAF for File chooser and option pane is so ugly under Gnome 3 so the
     * following code set Nimbus LAF before the File Chooser is called and
     * reverts back to original LAF when the user operation is complete
     */
    private void exportFollowup() {
        LookAndFeel llaf = UIManager.getLookAndFeel();
        String separator = File.separator;
        String path = System.getProperty("user.home") + separator + "bomico" + separator + "config" + separator + "followup.csv";
        File file = new File(path);
        jTable1.setModel(new Tmodel()); // update the table model
        toCSV(jTable1, file);

        JFileChooser fchooser = new JFileChooser(System.getProperty("user.home"));
        try {
            UIManager.setLookAndFeel(Utilities.nimbuslaf);



        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
        }
        SwingUtilities.updateComponentTreeUI(fchooser);
        File fileToSave = new File(System.getProperty("user.home") + separator + "followup.csv");
        fchooser.setFont(new java.awt.Font("Monospace", Font.PLAIN, 11));
        fchooser.setDialogTitle("Save Follow-up File");
        fchooser.setSelectedFile(fileToSave); // Setting the file chooser selected file must occur before it shows on screen in order to override it below
        int save = fchooser.showSaveDialog(Bim.this);
        File ftos = fchooser.getSelectedFile();

        if (save == JFileChooser.APPROVE_OPTION) {
            if (ftos.exists()) {
                int warning = JOptionPane.showConfirmDialog(this, "File Exists. Overwrite?", "Overwrite", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

                if (warning == JOptionPane.YES_OPTION) {
                    OutputStream output = null;
                    try {
                        File ff = fchooser.getSelectedFile();
                        output = new FileOutputStream(ff);
                        byte[] b = new byte[(int) file.length()];
                        FileInputStream fileInputStream = new FileInputStream(file);
                        fileInputStream.read(b);
                        for (int i = 0; i < b.length; i++) {
                            output.write(b[i]);


                        }

                    } catch (IOException ex) {
                        Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
                    } finally {
                        try {
                            output.flush();
                            output.close();
                            System.out.println("Followup File Exported as CSV File (Open it with your office application)");
                            jLabel17.setText("Follow-up File overwritten - It must retain .csv extension in order to open it with your office application");
                            UIManager.setLookAndFeel(llaf);
                            SwingUtilities.updateComponentTreeUI(this);


                        } catch (IOException | UnsupportedLookAndFeelException ex) {
                            Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                } else if (warning == JOptionPane.NO_OPTION) {
                    jLabel17.setText("Overwriting file operation canceled by user.");
                    System.out.println("Overwriting file operation canceled by user");
                    String claf = UIManager.getLookAndFeel().getName();
                    if ("Nimbus".equals(claf)) {
                        try {
                            UIManager.setLookAndFeel(llaf);
                            System.out.println("Setting LAF back to original " + UIManager.getLookAndFeel().getID());


                        } catch (UnsupportedLookAndFeelException ex) {
                            Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            } else {
                String claf = UIManager.getLookAndFeel().getName();
                if ("Nimbus".equals(claf)) {
                    try {
                        UIManager.setLookAndFeel(llaf);
                        System.out.println("Setting LAF back to original");


                    } catch (UnsupportedLookAndFeelException ex) {
                        Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                OutputStream output = null;
                try {
                    File ff = fchooser.getSelectedFile();
                    output = new FileOutputStream(ff);
                    byte[] b = new byte[(int) file.length()];
                    FileInputStream fileInputStream = new FileInputStream(file);
                    fileInputStream.read(b);
                    for (int i = 0; i < b.length; i++) {
                        output.write(b[i]);


                    }

                } catch (IOException ex) {
                    Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        output.flush();
                        output.close();
                        System.out.println("Followup File Exported as CSV File (Open it with your office application)");
                        jLabel17.setText("New File exported here: " + fchooser.getSelectedFile());
                        UIManager.setLookAndFeel(llaf);
                        SwingUtilities.updateComponentTreeUI(this);


                    } catch (IOException | UnsupportedLookAndFeelException ex) {
                        Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                System.out.println("End of New File Export Operation - ");

            }
        } else if (save == JFileChooser.CANCEL_OPTION) {
            String claf = UIManager.getLookAndFeel().getName();
            if ("Nimbus".equals(claf)) {
                try {
                    UIManager.setLookAndFeel(llaf);


                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            jLabel17.setText("Save operation canceled by user.");
        }
        System.err.println("Current LAF is: " + UIManager.getLookAndFeel().getID());
    }
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (evt.getSource() == jMenuItem4) {
            exportFollowup();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (evt.getSource() == jButton3) {
            this.addWindowListener(new ExitListener());
            System.exit(0);
            System.out.println("Application terminated by user.");
        };
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (evt.getSource() == jButton4) {
            jDialog1.setVisible(true);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            System.out.println("Your Screen Size is " + screenSize.width + " X " + screenSize.height);
            System.out.println("About Dialog opened");
        };
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (evt.getSource() == jButton5) {
            jDialog1.dispose();
            jTextPane1.setText(new Utilities().getAppInfos());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (evt.getSource() == jMenuItem5) {
            try {
                Utilities.setLaf(Utilities.metallaf);
                UIManager.setLookAndFeel(Utilities.metallaf);
                SwingUtilities.updateComponentTreeUI(this);
                SwingUtilities.updateComponentTreeUI(jDialog1);
                SwingUtilities.updateComponentTreeUI(jDialog2);
                System.out.println("LAF changed to Metal");


            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if (evt.getSource() == jMenuItem6) {
            try {
                UIManager.put("ToolTip.font", new FontUIResource(new Font("Dialog", Font.PLAIN, 11)));
                Utilities.setLaf(Utilities.gtklaf);
                UIManager.setLookAndFeel(Utilities.gtklaf);
                //   SwingUtilities.updateComponentTreeUI(Bim.this);
                SwingUtilities.updateComponentTreeUI(this);
                SwingUtilities.updateComponentTreeUI(jDialog1);
                SwingUtilities.updateComponentTreeUI(jDialog2);
                System.out.println("LAF changed to GTK");

            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        if (evt.getSource() == jMenuItem7) {
            try {
                // UIManager.put("nimbusBase", new Color(233, 233, 233));
                //UIManager.put("nimbusBlueGrey", new Color(233, 233, 233));
                UIManager.put("control", new Color(242, 241, 240));
                Utilities.setLaf(Utilities.nimbuslaf);
                UIManager.setLookAndFeel(Utilities.nimbuslaf);
                SwingUtilities.updateComponentTreeUI(this);
                SwingUtilities.updateComponentTreeUI(jDialog1);
                SwingUtilities.updateComponentTreeUI(jDialog2);
                System.out.println("LAF changed to Nimbus");


            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if (evt.getSource() == jMenuItem8) {
            try {
                Utilities.setLaf(Utilities.motiflaf);
                UIManager.setLookAndFeel(Utilities.motiflaf);
                SwingUtilities.updateComponentTreeUI(this);
                SwingUtilities.updateComponentTreeUI(jDialog1);
                SwingUtilities.updateComponentTreeUI(jDialog2);
                System.out.println("LAF changed to Motif");


            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (evt.getSource() == jButton6) {
            try {
                // In Case Text Pane is txt/html and file is text file
                // InputStream stream = getClass().getResourceAsStream("/resource/CREDITS.txt");
                // jTextPane1.read(stream, null);
                jTextPane1.setPage(getClass().getResource("/resource/CREDITS.html"));


            } catch (IOException ex) {
                Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (evt.getSource() == jButton7) {
            try {
                jTextPane1.setPage(getClass().getResource("/resource/LICENSE.html"));


            } catch (IOException ex) {
                Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (evt.getSource() == jButton8) {
            jTable1.setModel(new Tmodel());
            jDialog2.setVisible(true);

            //jTable1.setValueAt(object, row, column);

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (evt.getSource() == jButton9) {
            if (res != 0) {
                DecimalFormat df = new DecimalFormat("#.##");
                new Utilities().appendInXML(df.format(res));
                jButton9.setEnabled(false);
                System.out.println("BMI saved on file");
                jLabel17.setText("BMI saved");
            } else {
                System.out.println("Cannot save. BMI = 0");
                jLabel17.setText("Cannot save BMI");
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (evt.getSource() == jButton10) {
            jDialog2.repaint();
            jTable1.updateUI();
            jTable1.repaint();
            jDialog2.dispose();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        if (evt.getSource() == jMenuItem9) {
            jMenuItem9.setEnabled(false);
            String separator = File.separator;
            String p = System.getProperty("user.home");
            String localpath = p + separator + "bomico"
                    + separator + "config" + separator + "followup.xml";
            System.out.println(localpath);
            File xmlFile = new File(localpath);
            boolean exists = xmlFile.exists();

            int op =
                    JOptionPane.showConfirmDialog(jMenuItem9,
                    "Sure to Delete?",
                    "Follow-up",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    new javax.swing.ImageIcon(getClass().getResource("/resource/95.png")));
            try {
                if (op == JOptionPane.YES_OPTION) {
                    if (exists) {
                        xmlFile.delete();
                        System.out.println("- Followup.xml File Deleted");
                        jLabel17.setText("Followup.xml File Deleted");
                        // TODO Append confirmation text on Statut Bar 
                    }
                    System.out.println("Yes was pressed " + op);
                } else if (op == JOptionPane.NO_OPTION) {
                    System.out.println("No was pressed " + op);
                } else {
                    System.out.println("Close Clicked : " + op);
                }
            } finally {
                jMenuItem9.setEnabled(true);
            }


        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Task task = new Task();
        task.addPropertyChangeListener(new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent event) {
                if ("progress".equals(event.getPropertyName())) {
                    int progress = (Integer) event.getNewValue();
                    jProgressBar1.setIndeterminate(false);
                    jProgressBar1.setValue(progress);
                    jLabel17.setText(String.format("Completed %d%% of task. ", progress));
                    // computation();
                }
            }
        });
        task.execute();

        System.out.println("Computation Done.");
        jLabel17.setText("Computation done.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        if (evt.getSource() == jSlider1) {
            String sv = String.valueOf(jSlider1.getValue());
            jLabel20.setText("( " + sv + " Years)");
            jLabel17.setText("You moved the height slider to " + sv);
        }
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider4StateChanged
        // HEIGHT
        if (evt.getSource() == jSlider4) {
            String sv = String.valueOf(jSlider4.getValue());
            String fi = utils.convertHeight(jSlider4.getValue());
            jLabel12.setText("(" + sv + " Cm / " + fi + " )");
            jLabel17.setText("You moved the height slider to "
                    + sv + " centimeters" + " / " + fi);
            // feet = cm / 30.48
        }
    }//GEN-LAST:event_jSlider4StateChanged

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3StateChanged
        // WEIGHT
        if (evt.getSource() == jSlider3) {
            String sv = String.valueOf(jSlider3.getValue());
            double svp = utils.convertWeight(jSlider3.getValue());
            jLabel11.setText("(" + sv + " Kg / " + svp + " Pounds )");
            jLabel17.setText("You moved the weight slider to " + sv + " Kgs" + " / " + svp + " Pounds");
            // kg x  2.2 = pounds
        }
    }//GEN-LAST:event_jSlider3StateChanged

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        try {
            Utilities util = new Utilities();
            util.pasteSynthFile();
            SynthLookAndFeel laf = new SynthLookAndFeel();
            String fsep = File.separator;
            String synthpath = System.getProperty("user.home") + fsep + "bomico" + fsep + "config" + fsep + "synthlaf.xml";
            laf.load(new File(synthpath).toURL());
            UIManager.setLookAndFeel(laf);
            SwingUtilities.updateComponentTreeUI(this);
            SwingUtilities.updateComponentTreeUI(jDialog1);
            SwingUtilities.updateComponentTreeUI(jDialog2);


        } catch (ParseException | IOException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        /**
         * Use external LAF named Liquid
         */
        if (evt.getSource() == jMenuItem11) {
            try {
                com.birosoft.liquid.LiquidLookAndFeel.setLiquidDecorations(true, "panther");
                javax.swing.UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
                // if you want decorations for frames and dialogs you can put this two lines
                //
                // JFrame.setDefaultLookAndFeelDecorated(true);	// to decorate frames 
                //JDialog.setDefaultLookAndFeelDecorated(true);	// to decorate dialogs 
                //
                // or put this one line
                //
                // com.birosoft.liquid.LiquidLookAndFeel.setLiquidDecorations(true);
                //
                // or if you want to use Apple's Panther window decoration
                //
                com.birosoft.liquid.LiquidLookAndFeel.setLiquidDecorations(true, "panther");
                SwingUtilities.updateComponentTreeUI(this);
                SwingUtilities.updateComponentTreeUI(jDialog1);
                SwingUtilities.updateComponentTreeUI(jDialog2);


            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, null, ex);
            }


        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed

        utils.setPreferences(utils.MORPH_PREF, jComboBox3.getSelectedItem());
        utils.setPreferences(utils.FORMULA_PREF, jComboBox4.getSelectedItem());
        utils.setPreferences(utils.AGE_PREF, jSlider1.getValue());
        utils.setPreferences(utils.HEIGHT_PREF, jSlider4.getValue());
        utils.setPreferences(utils.WEIGHT_PREF, jSlider3.getValue());
        utils.setPreferences(utils.GENDER_PREF, jComboBox1.getSelectedItem());
        utils.setPreferences(utils.ACTIVITY_PREF, jComboBox2.getSelectedItem());
        utils.setPreferences(utils.LAF_PREF, Utilities.laf);
        jLabel17.setText("Preferences saved");
        // Integer.parseInt(utils.prefs.get(utils.HEIGHT_PREF, "170"))
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        try {
            utils.prefs.clear();
            jLabel17.setText("Preferences cleared");
        } catch (BackingStoreException ex) {
            Logger.getLogger(Bim.class.getName()).log(Level.SEVERE, "Action performed by jmenuitem13", ex);
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        if (evt.getSource() == jTextField4) {
            String pw = new DecimalFormat("#.##").format(c.getIweight() * 2.20462262);
            jLabel17.setText("Ideal weight is: "+pw+" pounds");
        }
    }//GEN-LAST:event_jTextField4MouseClicked

    // SEPARATION
    /**
     * Extension of Swing Worker to use for Progress bar simulation
     */
    public class Task extends SwingWorker<Void, Void> {

        @Override
        protected Void doInBackground() throws Exception {
            Random random = new Random();
            int progress = 0;
            //Initialize progress property.
            setProgress(0);
            //Sleep for at least 50 ms to simulate "startup".
            try {
                Thread.sleep(50 + random.nextInt(200));
            } catch (InterruptedException iex) {
                System.err.println(iex);
            }
            while (progress < 100) {
                //Sleep for up to 50 mili second.
                try {
                    Thread.sleep(random.nextInt(50));
                } catch (InterruptedException iex) {
                    System.err.println(iex);
                }
                //Make random progress.
                progress += random.nextInt(10);
                setProgress(Math.min(progress, 100));

            }
            computation();
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        new Utilities().pasteSplashFile();

        /*
         * Set the look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        // com.sun.java.swing.plaf.gtk.GTKLookAndFeel
        // javax.swing.plaf.metal.MetalLookAndFeel

        try {
            Utilities utility = new Utilities();
            // Set cross-platform Java L&F (also called "Metal")
            UIManager.setLookAndFeel(utility.prefs.get(utility.LAF_PREF, UIManager.getSystemLookAndFeelClassName()));
            //getCrossPlatformLookAndFeelClassName());


        } catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /*
         * try { for (javax.swing.UIManager.LookAndFeelInfo info :
         * javax.swing.UIManager.getInstalledLookAndFeels()) { if
         * ("Nimbus".equals(info.getName())) {
         * javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
         * // javax.swing.UIManager.setLookAndFeel(info.getClassName()); break;
         * } } } catch (ClassNotFoundException ex) {
         * java.util.logging.Logger.getLogger(Bim.class.getName()).log(java.util.logging.Level.SEVERE,
         * null, ex); } catch (InstantiationException ex) {
         * java.util.logging.Logger.getLogger(Bim.class.getName()).log(java.util.logging.Level.SEVERE,
         * null, ex); } catch (IllegalAccessException ex) {
         * java.util.logging.Logger.getLogger(Bim.class.getName()).log(java.util.logging.Level.SEVERE,
         * null, ex); } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         * java.util.logging.Logger.getLogger(Bim.class.getName()).log(java.util.logging.Level.SEVERE,
         * null, ex); }
         */
        //</editor-fold>

        /*
         * Create and display the form
         */

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override // The override annotation was added manually
            public void run() {
                Bim bim = new Bim();
                //Loading the location of the image in the variable url.
                URL url = URLClassLoader.getSystemResource("resource/pingu.png");
                bim.setIconImage(new ImageIcon(url).getImage()); // seting the icon to the JFrame

                //bim.setIconImage(Toolkit.getDefaultToolkit().getImage("/resource/pingu.png"));
                bim.setVisible(true);
            }
        });
    }
    // Custom Declaration
    double res;
    Utilities utils = new Utilities();
    Computer c = new Computer();
    //
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}

/**
 * Class to allow exiting the GUI
 *
 * @author Hanynowsky <hanynowsky@gmail.com>
 */
class ExitListener extends WindowAdapter {

    @Override
    public void windowClosing(WindowEvent event) {
        System.exit(0);
    }
}
